SELECT ADMIDATE,
COUNT(*) admissions
FROM HES_APC.dbo.[vHES_APC_Flat]
WHERE STARTAGE BETWEEN 15 AND 64
AND ADMIMETH IN ('21', '22', '23', '24', '25', '2A', '2B', '2C', '2D', '28')
AND EPIORDER = 1
GROUP BY ADMIDATE
